CMTPATH=/storage/epp2/t2k/software/ND280/v9r7p9
CMT_tag=$(tag)
CMTROOT=/storage/epp2/t2k/software/CMT/v1r20p20081118
CMT_root=/storage/epp2/t2k/software/CMT/v1r20p20081118
CMTVERSION=v1r20p20081118
cmt_hardware_query_command=uname -m
cmt_hardware=`$(cmt_hardware_query_command)`
cmt_system_version_query_command=${CMTROOT}/mgr/cmt_linux_version.sh | ${CMTROOT}/mgr/cmt_filter_version.sh
cmt_system_version=`$(cmt_system_version_query_command)`
cmt_compiler_version_query_command=${CMTROOT}/mgr/cmt_gcc_version.sh | ${CMTROOT}/mgr/cmt_filter3_version.sh
cmt_compiler_version=`$(cmt_compiler_version_query_command)`
PATH=myND280/amd64_linux26:/storage/epp2/t2k/software/ND280/v9r7p9/oaAnalysis/v4r37p5/amd64_linux26:/storage/epp2/t2k/software/ND280/v9r7p9/oaRecon/v3r5p5/amd64_linux26:/storage/epp2/t2k/software/ND280/v9r7p9/smrdCalib/v1r13/amd64_linux26:/storage/epp2/t2k/software/ND280/v9r7p9/p0decalRecon/v0r19/amd64_linux26:/storage/epp2/t2k/software/ND280/v9r7p9/p0dRecon/v7r3p9/amd64_linux26:/storage/epp2/t2k/software/ND280/v9r7p9/ecalRecon/v8r7p7/amd64_linux26:/storage/epp2/t2k/software/ND280/v9r7p9/trackerRecon/v0r15p9/amd64_linux26:/storage/epp2/t2k/software/ND280/v9r7p9/fgdRecon/v3r5p1/amd64_linux26:/storage/epp2/t2k/software/ND280/v9r7p9/tpcRecon/v5r17p1/amd64_linux26:/storage/epp2/t2k/software/ND280/v9r7p9/sbcat/v4r13p1/amd64_linux26:/storage/epp2/t2k/software/ND280/v9r7p9/oaCalib/v2r17p5/amd64_linux26:/storage/epp2/t2k/software/ND280/v9r7p9/oaApplyAlign/v0r5/amd64_linux26:/storage/epp2/t2k/software/ND280/v9r7p9/tfbApplyCalib/v2r3p3/amd64_linux26:/storage/epp2/t2k/software/ND280/v9r7p9/fgdRawData/v1r21/amd64_linux26:/storage/epp2/t2k/software/ND280/v9r7p9/oaChanInfo/v1r9p1/amd64_linux26:/storage/epp2/t2k/software/ND280/v9r7p9/oaUnpack/v3r3/amd64_linux26:/storage/epp2/t2k/software/ND280/v9r7p9/oaDataQuality/v1r5p1/src:/storage/epp2/t2k/software/ND280/v9r7p9/oaDataQuality/v1r5p1/amd64_linux26:/storage/epp2/t2k/software/ND280/v9r7p9/oaBeamData/v0r11/amd64_linux26:/storage/epp2/t2k/software/ND280/v9r7p9/oaGeomInfo/v4r5/amd64_linux26:/storage/epp2/t2k/software/ND280/v9r7p9/CLHEP/v2r0p4n05/amd64_linux26/bin:/storage/epp2/t2k/software/ND280/v9r7p9/oaUtility/v4r9p5/amd64_linux26:/storage/epp2/t2k/software/ND280/v9r7p9/magnetCalib/v3r7/amd64_linux26:/storage/epp2/t2k/software/ND280/v9r7p9/oaOfflineDatabase/v1r5/amd64_linux26:/storage/epp2/t2k/software/ND280/v9r7p9/MinosDBI/v1r1/amd64_linux26:/storage/epp2/t2k/software/ND280/v9r7p9/oaSlowControlDatabase/v1r5/amd64_linux26:/storage/epp2/t2k/software/ND280/v9r7p9/oaRuntimeParameters/v0r5/amd64_linux26:/storage/epp2/t2k/software/ND280/v9r7p9/oaRawEvent/v3r19/amd64_linux26:/storage/epp2/t2k/software/ND280/v9r7p9/oaEvent/v8r5p1/amd64_linux26:/storage/epp2/t2k/software/ND280/v9r7p9/testBase/v1r13/scripts:/storage/epp2/t2k/software/ND280/v9r7p9/testBase/v1r13/amd64_linux26:/storage/epp2/t2k/software/ND280/v9r7p9/ROOT/v5r28p00n01/amd64_linux26/bin:/storage/epp2/t2k/software/ND280/v9r7p9/MYSQL/v5r051an01/amd64_linux26/bin:/storage/epp2/t2k/software/ND280/v9r7p9/EXTERN/v3r5/scripts:/storage/epp2/t2k/software/ND280/v9r7p9/nd280Policy/v2r35/scripts:/storage/epp2/t2k/software/CMT/v1r20p20081118/${CMTBIN}:/storage/epp2/t2k/software/ND280/v9r7p9/atmPitSim/v0r3/amd64_linux26:/storage/epp2/t2k/software/ND280/v9r7p9/oaCosmicTrigger/v0r3/amd64_linux26:/storage/epp2/t2k/software/ND280/v9r7p9/ecalTestBeam/v0r5/amd64_linux26:/storage/epp2/t2k/software/ND280/v9r7p9/oaCherryPicker/v0r9/amd64_linux26:/storage/epp2/t2k/software/ND280/v9r7p9/eventDisplay/v3r43/amd64_linux26:/storage/epp2/t2k/software/ND280/v9r7p9/soffTasks/v0r1/app:/storage/epp2/t2k/software/ND280/v9r7p9/soffTasks/v0r1/amd64_linux26:/storage/epp2/t2k/software/ND280/v9r7p9/ecalCalib/v2r3/amd64_linux26:/storage/epp2/t2k/software/ND280/v9r7p9/mppcCalib/v1r13/amd64_linux26:/storage/epp2/t2k/software/ND280/v9r7p9/tfbCalib/v1r25/amd64_linux26:/storage/epp2/t2k/software/ND280/v9r7p9/oaAlignTools/v0r3p1/amd64_linux26:/storage/epp2/t2k/software/ND280/v9r7p9/elecSim/v6r7p1/amd64_linux26:/storage/epp2/t2k/software/ND280/v9r7p9/nd280mc/v4r41/amd64_linux26:/storage/epp2/t2k/software/ND280/v9r7p9/ingridUtils/v1r1/amd64_linux26:/storage/epp2/t2k/software/ND280/v9r7p9/nd280Control/v1r47/app:/storage/epp2/t2k/software/ND280/v9r7p9/GEANT/v9r3p02n00/:/storage/epp2/t2k/software/ND280/v9r7p9/nd280/v9r7p9/amd64_linux26:/warwick/maui/default/bin:/usr/local/bin:/usr/bin:/bin:/usr/bin/X11:/usr/X11R6/bin:/usr/games:/opt/kde3/bin:/warwick/iraf/bin:/usr/lib/mit/bin:/usr/lib/mit/sbin:/usr/NX/bin:/usr/lib/qt3/bin:/warwick/scilab/4.1/bin:/warwick/visit/linux-x86_64/bin:/storage/epp2/epp_software/2010.0/roodaf/5.30.00/x86_64/gnu/4.5.0/bin:/storage/epp2/t2k/software/ND280/v9r7p9/oaEvent/v8r5p1/scripts
CLASSPATH=/storage/epp2/t2k/software/CMT/v1r20p20081118/java
debug_option=-g
cc=gcc
ccomp=$(cc) -c $(includes) $(cdebugflags) $(cflags) $(pp_cflags)
clink=$(cc) $(clinkflags) $(cdebugflags)
ppcmd=-I
preproc=c++ -MD -c 
cpp=g++
cppflags=-g -pipe -O -Wall -ansi -Wctor-dtor-privacy -Wnon-virtual-dtor -fpic -Woverloaded-virtual 
pp_cppflags=-D_GNU_SOURCE
cppcomp=$(cpp) -c $(includes) $(cppdebugflags) $(cppflags) $(pp_cppflags)
cpplink=$(cpp) $(cpplinkflags) $(cppdebugflags)
for=g77
fflags=$(debug_option)
fcomp=$(for) -c $(fincludes) $(fflags) $(pp_fflags)
flink=$(for) $(flinkflags)
javacomp=javac -classpath $(src):$(CLASSPATH) 
javacopy=cp
jar=jar
X11_cflags=-I/usr/include
Xm_cflags=-I/usr/include
X_linkopts=-L/usr/X11R6/lib -lXm -lXt -lXext -lX11 -lm
lex=lex $(lexflags)
yaccflags= -l -d 
yacc=yacc $(yaccflags)
ar=ar cr
ranlib=ranlib
make_shlib=${CMTROOT}/mgr/cmt_make_shlib_common.sh extract
shlibsuffix=so
shlibbuilder=g++ $(cmt_installarea_linkopts) 
shlibflags=-shared
symlink=/bin/ln -fs 
symunlink=/bin/rm -f 
library_install_command=${symlink}
build_library_links=$(cmtexe) build library_links -tag=$(tags)
remove_library_links=$(cmtexe) remove library_links -tag=$(tags)
cmtexe=${CMTROOT}/${CMTBIN}/cmt.exe
build_prototype=$(cmtexe) build prototype
build_dependencies=$(cmtexe) -tag=$(tags) build dependencies
build_triggers=$(cmtexe) build triggers
implied_library_prefix=-l
SHELL=/bin/sh
q="
src=../src/
doc=../doc/
inc=../src/
mgr=../cmt/
application_suffix=.exe
library_prefix=lib
lock_command=lockfile 
unlock_command=rm -rf 
lock_name=cmt
lock_suffix=.lock
lock_file=${lock_name}${lock_suffix}
MAKEFLAGS= --no-print-directory 
gmake_hosts=lx1 rsplus lxtest as7 dxplus ax7 hp2 aleph hp1 hpplus papou1-fe atlas
make_hosts=virgo-control1 rio0a vmpc38a
everywhere=hosts
install_command=cp 
uninstall_command=/bin/rm -f 
cmt_installarea_command=ln -fs 
cmt_uninstallarea_command=/bin/rm -f 
cmt_install_area_command=$(cmt_installarea_command)
cmt_uninstall_area_command=$(cmt_uninstallarea_command)
cmt_install_action=$(CMTROOT)/mgr/cmt_install_action.sh
cmt_installdir_action=$(CMTROOT)/mgr/cmt_installdir_action.sh
cmt_uninstall_action=$(CMTROOT)/mgr/cmt_uninstall_action.sh
cmt_uninstalldir_action=$(CMTROOT)/mgr/cmt_uninstalldir_action.sh
mkdir=mkdir
cmt_cvs_protocol_level=v1r1
cmt_installarea_prefix=InstallArea
CMT_PATH_remove_regexp=/[^/]*/
CMT_PATH_remove_share_regexp=/share/
NEWCMTCONFIG=x86_64-suse113-gcc450
myND280_tag=$(tag)
MYND280ROOT=/home/physics/phuidv/Documents/t2kstuff/recon/myND280/v0r0
myND280_root=/home/physics/phuidv/Documents/t2kstuff/recon/myND280/v0r0
MYND280VERSION=v0r0
oaEvent_tag=$(tag)
OAEVENTROOT=/storage/epp2/t2k/software/ND280/v9r7p9/oaEvent/v8r5p1
oaEvent_root=/storage/epp2/t2k/software/ND280/v9r7p9/oaEvent/v8r5p1
OAEVENTVERSION=v8r5p1
oaEvent_cmtpath=/storage/epp2/t2k/software/ND280/v9r7p9
oaEvent_project=ND280
oaEvent_project_release=v9r7p9
nd280Policy_tag=$(tag)
ND280POLICYROOT=/storage/epp2/t2k/software/ND280/v9r7p9/nd280Policy/v2r35
nd280Policy_root=/storage/epp2/t2k/software/ND280/v9r7p9/nd280Policy/v2r35
ND280POLICYVERSION=v2r35
nd280Policy_cmtpath=/storage/epp2/t2k/software/ND280/v9r7p9
nd280Policy_project=ND280
nd280Policy_project_release=v9r7p9
ROOT_tag=$(tag)
ROOTROOT=/storage/epp2/t2k/software/ND280/v9r7p9/ROOT/v5r28p00n01
ROOT_root=/storage/epp2/t2k/software/ND280/v9r7p9/ROOT/v5r28p00n01
ROOTVERSION=v5r28p00n01
ROOT_cmtpath=/storage/epp2/t2k/software/ND280/v9r7p9
ROOT_project=ND280
ROOT_project_release=v9r7p9
EXTERN_tag=$(tag)
EXTERNROOT=/storage/epp2/t2k/software/ND280/v9r7p9/EXTERN/v3r5
EXTERN_root=/storage/epp2/t2k/software/ND280/v9r7p9/EXTERN/v3r5
EXTERNVERSION=v3r5
EXTERN_cmtpath=/storage/epp2/t2k/software/ND280/v9r7p9
EXTERN_project=ND280
EXTERN_project_release=v9r7p9
MYSQL_tag=$(tag)
MYSQLROOT=/storage/epp2/t2k/software/ND280/v9r7p9/MYSQL/v5r051an01
MYSQL_root=/storage/epp2/t2k/software/ND280/v9r7p9/MYSQL/v5r051an01
MYSQLVERSION=v5r051an01
MYSQL_cmtpath=/storage/epp2/t2k/software/ND280/v9r7p9
MYSQL_project=ND280
MYSQL_project_release=v9r7p9
LD_LIBRARY_PATH=myND280/amd64_linux26:/storage/epp2/t2k/software/ND280/v9r7p9/oaAnalysis/v4r37p5/amd64_linux26:/storage/epp2/t2k/software/ND280/v9r7p9/oaRecon/v3r5p5/amd64_linux26:/storage/epp2/t2k/software/ND280/v9r7p9/smrdRecon/v3r3p3/amd64_linux26:/storage/epp2/t2k/software/ND280/v9r7p9/smrdCalib/v1r13/amd64_linux26:/storage/epp2/t2k/software/ND280/v9r7p9/p0decalRecon/v0r19/amd64_linux26:/storage/epp2/t2k/software/ND280/v9r7p9/p0dRecon/v7r3p9/amd64_linux26:/storage/epp2/t2k/software/ND280/v9r7p9/ecalRecon/v8r7p7/amd64_linux26:/storage/epp2/t2k/software/ND280/v9r7p9/trackerRecon/v0r15p9/amd64_linux26:/storage/epp2/t2k/software/ND280/v9r7p9/fgdRecon/v3r5p1/amd64_linux26:/storage/epp2/t2k/software/ND280/v9r7p9/tpcRecon/v5r17p1/amd64_linux26:/storage/epp2/t2k/software/ND280/v9r7p9/sbcat/v4r13p1/amd64_linux26:/storage/epp2/t2k/software/ND280/v9r7p9/oaCalib/v2r17p5/amd64_linux26:/storage/epp2/t2k/software/ND280/v9r7p9/oaApplyAlign/v0r5/amd64_linux26:/storage/epp2/t2k/software/ND280/v9r7p9/tfbApplyCalib/v2r3p3/amd64_linux26:/storage/epp2/t2k/software/ND280/v9r7p9/fgdRawData/v1r21/amd64_linux26:/storage/epp2/t2k/software/ND280/v9r7p9/oaChanInfo/v1r9p1/amd64_linux26:/storage/epp2/t2k/software/ND280/v9r7p9/oaUnpack/v3r3/amd64_linux26:/storage/epp2/t2k/software/ND280/v9r7p9/oaDataQuality/v1r5p1/amd64_linux26:/storage/epp2/t2k/software/ND280/v9r7p9/oaBeamData/v0r11/amd64_linux26:/storage/epp2/t2k/software/ND280/v9r7p9/oaRecPack/v2r25p9/amd64_linux26:/storage/epp2/t2k/software/ND280/v9r7p9/oaGeomInfo/v4r5/amd64_linux26:/storage/epp2/t2k/software/ND280/v9r7p9/RECPACK/v1r17p1/amd64_linux26:/storage/epp2/t2k/software/ND280/v9r7p9/CLHEP/v2r0p4n05/amd64_linux26/lib:/storage/epp2/t2k/software/ND280/v9r7p9/oaUtility/v4r9p5/amd64_linux26:/storage/epp2/t2k/software/ND280/v9r7p9/magnetCalib/v3r7/amd64_linux26:/storage/epp2/t2k/software/ND280/v9r7p9/oaOfflineDatabase/v1r5/amd64_linux26:/storage/epp2/t2k/software/ND280/v9r7p9/MinosDBI/v1r1/amd64_linux26:/storage/epp2/t2k/software/ND280/v9r7p9/oaSlowControlDatabase/v1r5/amd64_linux26:/storage/epp2/t2k/software/ND280/v9r7p9/oaRuntimeParameters/v0r5/amd64_linux26:/storage/epp2/t2k/software/ND280/v9r7p9/oaRawEvent/v3r19/amd64_linux26:/storage/epp2/t2k/software/ND280/v9r7p9/oaEvent/v8r5p1/amd64_linux26:/storage/epp2/t2k/software/ND280/v9r7p9/ROOT/v5r28p00n01/amd64_linux26/lib/root:/storage/epp2/t2k/software/ND280/v9r7p9/MYSQL/v5r051an01/amd64_linux26/lib/mysql:/storage/epp2/t2k/software/ND280/v9r7p9/atmPitSim/v0r3/amd64_linux26:/storage/epp2/t2k/software/ND280/v9r7p9/oaCosmicTrigger/v0r3/amd64_linux26:/storage/epp2/t2k/software/ND280/v9r7p9/ecalTestBeam/v0r5/amd64_linux26:/storage/epp2/t2k/software/ND280/v9r7p9/eventDisplay/v3r43/amd64_linux26:/storage/epp2/t2k/software/ND280/v9r7p9/ingridRecon/v2r1/amd64_linux26:/storage/epp2/t2k/software/ND280/v9r7p9/soffTasks/v0r1/amd64_linux26:/storage/epp2/t2k/software/ND280/v9r7p9/ecalCalib/v2r3/amd64_linux26:/storage/epp2/t2k/software/ND280/v9r7p9/mppcCalib/v1r13/amd64_linux26:/storage/epp2/t2k/software/ND280/v9r7p9/tfbCalib/v1r25/amd64_linux26:/storage/epp2/t2k/software/ND280/v9r7p9/oaAlignTools/v0r3p1/amd64_linux26:/storage/epp2/t2k/software/ND280/v9r7p9/elecSim/v6r7p1/amd64_linux26:/storage/epp2/t2k/software/ND280/v9r7p9/nd280mc/v4r41/amd64_linux26:/storage/epp2/t2k/software/ND280/v9r7p9/ingridUtils/v1r1/amd64_linux26:/storage/epp2/t2k/software/ND280/v9r7p9/GEANT/v9r3p02n00/amd64_linux26/Linux-g++:/storage/epp2/t2k/software/ND280/v9r7p9/GEANT/v9r3p02n00/amd64_linux26/plists/Linux-g++
MYSQL_linkopts=`$(MYSQLROOT)/$(MYSQL_tag)/bin/mysql_config  --libs`
MYSQL_BASE_DIR=/storage/epp2/t2k/software/ND280/v9r7p9/MYSQL/v5r051an01/amd64_linux26
MYSQL_LIB_DIR=${MYSQL_BASE_DIR}/lib/mysql
MYSQL_INCLUDE_DIR=${MYSQL_BASE_DIR}/include/mysql
MAKFLAGS=--no-print-directory
ROOT_PATH=$(ROOTROOT)/$(tag)
ROOT_BIN=$(ROOT_PATH)/bin
ROOT_LIB=$(ROOT_PATH)/lib/root
ROOTSYS=/storage/epp2/t2k/software/ND280/v9r7p9/ROOT/v5r28p00n01/amd64_linux26
PYTHONPATH=/storage/epp2/t2k/software/ND280/v9r7p9/oaDataQuality/v1r5p1/src:/storage/epp2/t2k/software/ND280/v9r7p9/soffTasks/v0r1/share/daemon:/storage/epp2/t2k/software/ND280/v9r7p9/soffTasks/v0r1/share/ecal:/storage/epp2/t2k/software/ND280/v9r7p9/soffTasks/v0r1/share/fgd:/storage/epp2/t2k/software/ND280/v9r7p9/nd280Control/v1r47/modules:/storage/epp2/epp_software/2010.0/roodaf/5.30.00/x86_64/gnu/4.5.0/lib/root:${ROOTSYS}/lib/root
ROOT_linkopts=`$(ROOT_BIN)/root-config --glibs` -lEG -lGeom -lMinuit -lFumili -lXMLIO -lXMLParser
ROOT_cppflags=-DROOT_USED `$(ROOT_BIN)/root-config --cflags` -Wno-long-long
ROOT_stamps=$(ROOTROOT)/$(ROOTCONFIG)/ROOT.stamp
dict=../dict/
rootcint=$(ROOT_BIN)/rootcint
testBase_tag=$(tag)
TESTBASEROOT=/storage/epp2/t2k/software/ND280/v9r7p9/testBase/v1r13
testBase_root=/storage/epp2/t2k/software/ND280/v9r7p9/testBase/v1r13
TESTBASEVERSION=v1r13
testBase_cmtpath=/storage/epp2/t2k/software/ND280/v9r7p9
testBase_project=ND280
testBase_project_release=v9r7p9
testBase_cppflags= -DTESTBASE_USED 
install_dir=$(OAOFFLINEDATABASEROOT)/$(oaOfflineDatabase_tag)
oaEvent_cppflags= -DOAEVENT_USED 
oaEvent_linkopts= -L$(OAEVENTROOT)/$(oaEvent_tag) -loaEvent 
oaEvent_stamps= $(OAEVENTROOT)/$(oaEvent_tag)/oaEvent.stamp
oaAnalysis_tag=$(tag)
OAANALYSISROOT=/storage/epp2/t2k/software/ND280/v9r7p9/oaAnalysis/v4r37p5
oaAnalysis_root=/storage/epp2/t2k/software/ND280/v9r7p9/oaAnalysis/v4r37p5
OAANALYSISVERSION=v4r37p5
oaAnalysis_cmtpath=/storage/epp2/t2k/software/ND280/v9r7p9
oaAnalysis_project=ND280
oaAnalysis_project_release=v9r7p9
oaUtility_tag=$(tag)
OAUTILITYROOT=/storage/epp2/t2k/software/ND280/v9r7p9/oaUtility/v4r9p5
oaUtility_root=/storage/epp2/t2k/software/ND280/v9r7p9/oaUtility/v4r9p5
OAUTILITYVERSION=v4r9p5
oaUtility_cmtpath=/storage/epp2/t2k/software/ND280/v9r7p9
oaUtility_project=ND280
oaUtility_project_release=v9r7p9
magnetCalib_tag=$(tag)
MAGNETCALIBROOT=/storage/epp2/t2k/software/ND280/v9r7p9/magnetCalib/v3r7
magnetCalib_root=/storage/epp2/t2k/software/ND280/v9r7p9/magnetCalib/v3r7
MAGNETCALIBVERSION=v3r7
magnetCalib_cmtpath=/storage/epp2/t2k/software/ND280/v9r7p9
magnetCalib_project=ND280
magnetCalib_project_release=v9r7p9
oaSlowControlDatabase_tag=$(tag)
OASLOWCONTROLDATABASEROOT=/storage/epp2/t2k/software/ND280/v9r7p9/oaSlowControlDatabase/v1r5
oaSlowControlDatabase_root=/storage/epp2/t2k/software/ND280/v9r7p9/oaSlowControlDatabase/v1r5
OASLOWCONTROLDATABASEVERSION=v1r5
oaSlowControlDatabase_cmtpath=/storage/epp2/t2k/software/ND280/v9r7p9
oaSlowControlDatabase_project=ND280
oaSlowControlDatabase_project_release=v9r7p9
oaRawEvent_tag=$(tag)
OARAWEVENTROOT=/storage/epp2/t2k/software/ND280/v9r7p9/oaRawEvent/v3r19
oaRawEvent_root=/storage/epp2/t2k/software/ND280/v9r7p9/oaRawEvent/v3r19
OARAWEVENTVERSION=v3r19
oaRawEvent_cmtpath=/storage/epp2/t2k/software/ND280/v9r7p9
oaRawEvent_project=ND280
oaRawEvent_project_release=v9r7p9
oaRawEvent_cppflags= -DOARAWEVENT_USED 
oaRawEvent_linkopts= -L$(OARAWEVENTROOT)/$(oaRawEvent_tag) -loaRawEvent 
oaRawEvent_stamps= $(OARAWEVENTROOT)/$(oaRawEvent_tag)/oaRawEvent.stamp
oaRuntimeParameters_tag=$(tag)
OARUNTIMEPARAMETERSROOT=/storage/epp2/t2k/software/ND280/v9r7p9/oaRuntimeParameters/v0r5
oaRuntimeParameters_root=/storage/epp2/t2k/software/ND280/v9r7p9/oaRuntimeParameters/v0r5
OARUNTIMEPARAMETERSVERSION=v0r5
oaRuntimeParameters_cmtpath=/storage/epp2/t2k/software/ND280/v9r7p9
oaRuntimeParameters_project=ND280
oaRuntimeParameters_project_release=v9r7p9
oaRuntimeParameters_cppflags= -DOARUNTIMEPARAMETERS_USED 
oaRuntimeParameters_linkopts= -L$(OARUNTIMEPARAMETERSROOT)/$(oaRuntimeParameters_tag) -loaRuntimeParameters 
oaRuntimeParameters_stamps= $(OARUNTIMEPARAMETERSROOT)/$(oaRuntimeParameters_tag)/oaRuntimeParameters.stamp
oaSlowControlDatabase_cppflags= -DOASLOWCONTROLDATABASE_USED
oaSlowControlDatabase_linkopts= -L$(OASLOWCONTROLDATABASEROOT)/$(oaSlowControlDatabase_tag) -loaSlowControlDatabase 
oaSlowControlDatabase_stamps= $(OASLOWCONTROLDATABASEROOT)/$(oaSlowControlDatabase_tag)/oaSlowControlDatabase.stamp
oaOfflineDatabase_tag=$(tag)
OAOFFLINEDATABASEROOT=/storage/epp2/t2k/software/ND280/v9r7p9/oaOfflineDatabase/v1r5
oaOfflineDatabase_root=/storage/epp2/t2k/software/ND280/v9r7p9/oaOfflineDatabase/v1r5
OAOFFLINEDATABASEVERSION=v1r5
oaOfflineDatabase_cmtpath=/storage/epp2/t2k/software/ND280/v9r7p9
oaOfflineDatabase_project=ND280
oaOfflineDatabase_project_release=v9r7p9
MinosDBI_tag=$(tag)
MINOSDBIROOT=/storage/epp2/t2k/software/ND280/v9r7p9/MinosDBI/v1r1
MinosDBI_root=/storage/epp2/t2k/software/ND280/v9r7p9/MinosDBI/v1r1
MINOSDBIVERSION=v1r1
MinosDBI_cmtpath=/storage/epp2/t2k/software/ND280/v9r7p9
MinosDBI_project=ND280
MinosDBI_project_release=v9r7p9
MinosDBI_cppflags= -D MINOSDBI_USED 
MinosDBI_linkopts= -L$(MINOSDBIROOT)/$(MinosDBI_tag) -lMinosDBI 
MinosDBI_stamps= $(MINOSDBIROOT)/$(MinosDBI_tag)/MinosDBI.stamp
oaOfflineDatabase_cppflags= -DOAOFFLINEDATABASE_USED 
oaOfflineDatabase_linkopts= -L$(OAOFFLINEDATABASEROOT)/$(oaOfflineDatabase_tag) -loaOfflineDatabase 
oaOfflineDatabase_stamps= $(OAOFFLINEDATABASEROOT)/$(oaOfflineDatabase_tag)/oaOfflineDatabase.stamp
magnetCalib_cppflags= -DMAGNETCALIB_USED 
magnetCalib_linkopts= -L$(MAGNETCALIBROOT)/$(magnetCalib_tag) -lmagnetCalib 
magnetCalib_stamps= $(MAGNETCALIBROOT)/$(magnetCalib_tag)/magnetCalib.stamp
oaUtility_cppflags= -DOAUTILITY_USED 
oaUtility_linkopts= -L$(OAUTILITYROOT)/$(oaUtility_tag) -loaUtility 
oaUtility_stamps= $(OAUTILITYROOT)/$(oaUtility_tag)/oaUtility.stamp
oaRecPack_tag=$(tag)
OARECPACKROOT=/storage/epp2/t2k/software/ND280/v9r7p9/oaRecPack/v2r25p9
oaRecPack_root=/storage/epp2/t2k/software/ND280/v9r7p9/oaRecPack/v2r25p9
OARECPACKVERSION=v2r25p9
oaRecPack_cmtpath=/storage/epp2/t2k/software/ND280/v9r7p9
oaRecPack_project=ND280
oaRecPack_project_release=v9r7p9
RECPACK_tag=$(tag)
RECPACKROOT=/storage/epp2/t2k/software/ND280/v9r7p9/RECPACK/v1r17p1
RECPACK_root=/storage/epp2/t2k/software/ND280/v9r7p9/RECPACK/v1r17p1
RECPACKVERSION=v1r17p1
RECPACK_cmtpath=/storage/epp2/t2k/software/ND280/v9r7p9
RECPACK_project=ND280
RECPACK_project_release=v9r7p9
CLHEP_tag=$(tag)
CLHEPROOT=/storage/epp2/t2k/software/ND280/v9r7p9/CLHEP/v2r0p4n05
CLHEP_root=/storage/epp2/t2k/software/ND280/v9r7p9/CLHEP/v2r0p4n05
CLHEPVERSION=v2r0p4n05
CLHEP_cmtpath=/storage/epp2/t2k/software/ND280/v9r7p9
CLHEP_project=ND280
CLHEP_project_release=v9r7p9
CLHEP_cppflags= -DCLHEP_USED 
CLHEP_linkopts= -L$(CLHEPROOT)/$(CLHEP_tag)/lib -lCLHEP 
CLHEP_BASE_DIR=/storage/epp2/t2k/software/ND280/v9r7p9/CLHEP/v2r0p4n05/amd64_linux26
CLHEP_LIB_DIR=${CLHEP_BASE_DIR}/lib
CLHEP_INCLUDE_DIR=${CLHEP_BASE_DIR}/include
CLHEP_LIB=CLHEP
RECPACK_PATH=$(RECPACKROOT)/$(tag)
RECPACK_BIN=$(RECPACK_PATH)/bin
RECPACK_LIB=$(RECPACK_PATH)/lib/
RECPACK_cppflags= -DRECPACK_USED -I$(RECPACKROOT)/$(RECPACK_tag) 
RECPACK_linkopts= -L$(RECPACKROOT)/$(RECPACK_tag) -lrecpack 
oaGeomInfo_tag=$(tag)
OAGEOMINFOROOT=/storage/epp2/t2k/software/ND280/v9r7p9/oaGeomInfo/v4r5
oaGeomInfo_root=/storage/epp2/t2k/software/ND280/v9r7p9/oaGeomInfo/v4r5
OAGEOMINFOVERSION=v4r5
oaGeomInfo_cmtpath=/storage/epp2/t2k/software/ND280/v9r7p9
oaGeomInfo_project=ND280
oaGeomInfo_project_release=v9r7p9
oaGeomInfo_cppflags= -DOAGEOMINFO_USED 
oaGeomInfo_linkopts= -L$(OAGEOMINFOROOT)/$(oaGeomInfo_tag) -loaGeomInfo 
oaGeomInfo_stamps= $(OAGEOMINFOROOT)/$(oaGeomInfo_tag)/oaGeomInfo.stamp
oaRecPack_cppflags= -DOARECPACK_USED
oaRecPack_linkopts= -L$(OARECPACKROOT)/$(oaRecPack_tag) -loaRecPack 
oaRecPack_stamps= $(OARECPACKROOT)/$(oaRecPack_tag)/oaRecPack.stamp
oaBeamData_tag=$(tag)
OABEAMDATAROOT=/storage/epp2/t2k/software/ND280/v9r7p9/oaBeamData/v0r11
oaBeamData_root=/storage/epp2/t2k/software/ND280/v9r7p9/oaBeamData/v0r11
OABEAMDATAVERSION=v0r11
oaBeamData_cmtpath=/storage/epp2/t2k/software/ND280/v9r7p9
oaBeamData_project=ND280
oaBeamData_project_release=v9r7p9
oaBeamData_cppflags=-DOABEAMDATA_USED -I$(OABEAMDATAROOT)/$(oaBeamData_tag)
oaBeamData_linkopts=-L$(OABEAMDATAROOT)/$(oaBeamData_tag) -loaBeamData -lBeamData
oaBeamData_stamps= $(OABEAMDATAROOT)/$(oaBeamData_tag)/oaBeamData.stamp
oaDataQuality_tag=$(tag)
OADATAQUALITYROOT=/storage/epp2/t2k/software/ND280/v9r7p9/oaDataQuality/v1r5p1
oaDataQuality_root=/storage/epp2/t2k/software/ND280/v9r7p9/oaDataQuality/v1r5p1
OADATAQUALITYVERSION=v1r5p1
oaDataQuality_cmtpath=/storage/epp2/t2k/software/ND280/v9r7p9
oaDataQuality_project=ND280
oaDataQuality_project_release=v9r7p9
oaDataQuality_cppflags= -DOADATAQUALITY_USED 
oaDataQuality_linkopts= -L$(OADATAQUALITYROOT)/$(oaDataQuality_tag) -loaDataQuality 
oaDataQuality_stamps= $(OADATAQUALITYROOT)/$(oaDataQuality_tag)/oaDataQuality.stamp
GNUPLOT_LIB=/storage/epp2/t2k/software/ND280/v9r7p9/oaDataQuality/v1r5p1/src
CALIB_use=oaCalib *
RECON_use=oaRecon *
oaCalib_tag=$(tag)
OACALIBROOT=/storage/epp2/t2k/software/ND280/v9r7p9/oaCalib/v2r17p5
oaCalib_root=/storage/epp2/t2k/software/ND280/v9r7p9/oaCalib/v2r17p5
OACALIBVERSION=v2r17p5
oaCalib_cmtpath=/storage/epp2/t2k/software/ND280/v9r7p9
oaCalib_project=ND280
oaCalib_project_release=v9r7p9
fgdRawData_tag=$(tag)
FGDRAWDATAROOT=/storage/epp2/t2k/software/ND280/v9r7p9/fgdRawData/v1r21
fgdRawData_root=/storage/epp2/t2k/software/ND280/v9r7p9/fgdRawData/v1r21
FGDRAWDATAVERSION=v1r21
fgdRawData_cmtpath=/storage/epp2/t2k/software/ND280/v9r7p9
fgdRawData_project=ND280
fgdRawData_project_release=v9r7p9
oaUnpack_tag=$(tag)
OAUNPACKROOT=/storage/epp2/t2k/software/ND280/v9r7p9/oaUnpack/v3r3
oaUnpack_root=/storage/epp2/t2k/software/ND280/v9r7p9/oaUnpack/v3r3
OAUNPACKVERSION=v3r3
oaUnpack_cmtpath=/storage/epp2/t2k/software/ND280/v9r7p9
oaUnpack_project=ND280
oaUnpack_project_release=v9r7p9
oaUnpack_linkopts= -L$(OAUNPACKROOT)/$(oaUnpack_tag) -loaUnpack 
oaChanInfo_tag=$(tag)
OACHANINFOROOT=/storage/epp2/t2k/software/ND280/v9r7p9/oaChanInfo/v1r9p1
oaChanInfo_root=/storage/epp2/t2k/software/ND280/v9r7p9/oaChanInfo/v1r9p1
OACHANINFOVERSION=v1r9p1
oaChanInfo_cmtpath=/storage/epp2/t2k/software/ND280/v9r7p9
oaChanInfo_project=ND280
oaChanInfo_project_release=v9r7p9
oaChanInfo_cppflags= -DOACHANINFO_USED 
oaChanInfo_linkopts= -L$(OACHANINFOROOT)/$(oaChanInfo_tag) -loaChanInfo 
oaChanInfo_stamps= $(OACHANINFOROOT)/$(oaChanInfo_tag)/oaChanInfo.stamp
fgdRawData_cppflags= -DFGDRAWDATA_USED -I$(FGDRAWDATAROOT)/src/Data/ -I$(FGDRAWDATAROOT)/src/Tasks/ -I$(FGDRAWDATAROOT)/src/Database/ -I$(FGDRAWDATAROOT)/src/Display/ 
fgdRawData_linkopts= -L$(FGDRAWDATAROOT)/$(fgdRawData_tag) -lfgdRawData 
fgdRawData_stamps= $(FGDRAWDATAROOT)/$(fgdRawData_tag)/fgdRawData.stamp
tfbApplyCalib_tag=$(tag)
TFBAPPLYCALIBROOT=/storage/epp2/t2k/software/ND280/v9r7p9/tfbApplyCalib/v2r3p3
tfbApplyCalib_root=/storage/epp2/t2k/software/ND280/v9r7p9/tfbApplyCalib/v2r3p3
TFBAPPLYCALIBVERSION=v2r3p3
tfbApplyCalib_cmtpath=/storage/epp2/t2k/software/ND280/v9r7p9
tfbApplyCalib_project=ND280
tfbApplyCalib_project_release=v9r7p9
tfbApplyCalib_cppflags= -DTFBAPPLYCALIB_USED
tfbApplyCalib_linkopts= -L$(TFBAPPLYCALIBROOT)/$(tfbApplyCalib_tag) -ltfbApplyCalib 
oaApplyAlign_tag=$(tag)
OAAPPLYALIGNROOT=/storage/epp2/t2k/software/ND280/v9r7p9/oaApplyAlign/v0r5
oaApplyAlign_root=/storage/epp2/t2k/software/ND280/v9r7p9/oaApplyAlign/v0r5
OAAPPLYALIGNVERSION=v0r5
oaApplyAlign_cmtpath=/storage/epp2/t2k/software/ND280/v9r7p9
oaApplyAlign_project=ND280
oaApplyAlign_project_release=v9r7p9
oaApplyAlign_cppflags= -DOAAPPLYALIGN_USED 
oaApplyAlign_linkopts= -L$(OAAPPLYALIGNROOT)/$(oaApplyAlign_tag) -loaApplyAlign 
oaApplyAlign_stamps= $(OAAPPLYALIGNROOT)/$(oaApplyAlign_tag)/oaApplyAlign.stamp
oaCalib_cppflags= -DOACALIB_USED 
oaCalib_linkopts= -L$(OACALIBROOT)/$(oaCalib_tag) -loaCalib 
oaCalib_stamps= $(OACALIBROOT)/$(oaCalib_tag)/oaCalib.stamp
oaRecon_tag=$(tag)
OARECONROOT=/storage/epp2/t2k/software/ND280/v9r7p9/oaRecon/v3r5p5
oaRecon_root=/storage/epp2/t2k/software/ND280/v9r7p9/oaRecon/v3r5p5
OARECONVERSION=v3r5p5
oaRecon_cmtpath=/storage/epp2/t2k/software/ND280/v9r7p9
oaRecon_project=ND280
oaRecon_project_release=v9r7p9
trackerRecon_tag=$(tag)
TRACKERRECONROOT=/storage/epp2/t2k/software/ND280/v9r7p9/trackerRecon/v0r15p9
trackerRecon_root=/storage/epp2/t2k/software/ND280/v9r7p9/trackerRecon/v0r15p9
TRACKERRECONVERSION=v0r15p9
trackerRecon_cmtpath=/storage/epp2/t2k/software/ND280/v9r7p9
trackerRecon_project=ND280
trackerRecon_project_release=v9r7p9
tpcRecon_tag=$(tag)
TPCRECONROOT=/storage/epp2/t2k/software/ND280/v9r7p9/tpcRecon/v5r17p1
tpcRecon_root=/storage/epp2/t2k/software/ND280/v9r7p9/tpcRecon/v5r17p1
TPCRECONVERSION=v5r17p1
tpcRecon_cmtpath=/storage/epp2/t2k/software/ND280/v9r7p9
tpcRecon_project=ND280
tpcRecon_project_release=v9r7p9
sbcat_tag=$(tag)
SBCATROOT=/storage/epp2/t2k/software/ND280/v9r7p9/sbcat/v4r13p1
sbcat_root=/storage/epp2/t2k/software/ND280/v9r7p9/sbcat/v4r13p1
SBCATVERSION=v4r13p1
sbcat_cmtpath=/storage/epp2/t2k/software/ND280/v9r7p9
sbcat_project=ND280
sbcat_project_release=v9r7p9
sbcat_cppflags= -DSBCAT_USED 
sbcat_linkopts= -L$(SBCATROOT)/$(sbcat_tag) -lsbcat 
sbcat_stamps= $(SBCATROOT)/$(sbcat_tag)/sbcat.stamp
tpcRecon_cppflags= -DTPCRECON_USED 
tpcRecon_linkopts= -L$(TPCRECONROOT)/$(tpcRecon_tag) -ltpcRecon 
rpcRecon_stamps= $(TPCRECONROOT)/$(readelecSim_tag)/tpcRecon.stamp
myND280_linkopts= -L$(package)/$(tag) 
fgdRecon_tag=$(tag)
FGDRECONROOT=/storage/epp2/t2k/software/ND280/v9r7p9/fgdRecon/v3r5p1
fgdRecon_root=/storage/epp2/t2k/software/ND280/v9r7p9/fgdRecon/v3r5p1
FGDRECONVERSION=v3r5p1
fgdRecon_cmtpath=/storage/epp2/t2k/software/ND280/v9r7p9
fgdRecon_project=ND280
fgdRecon_project_release=v9r7p9
fgdRecon_cppflags= -DFGDRECON_USED
fgdRecon_linkopts= -L$(FGDRECONROOT)/$(fgdRecon_tag) -lfgdRecon 
fgdRecon_stamps= $(FGDRECONROOT)/$(fgdRecon_tag)/fgdRecon.stamp
trackerRecon_cppflags= -DTRACKERRECON_USED 
trackerRecon_linkopts= -L$(TRACKERRECONROOT)/$(trackerRecon_tag) -ltrackerRecon 
trackerRecon_stamps= $(TRACKERRECONROOT)/$(trackerRecon_tag)/trackerRecon.stamp
ecalRecon_tag=$(tag)
ECALRECONROOT=/storage/epp2/t2k/software/ND280/v9r7p9/ecalRecon/v8r7p7
ecalRecon_root=/storage/epp2/t2k/software/ND280/v9r7p9/ecalRecon/v8r7p7
ECALRECONVERSION=v8r7p7
ecalRecon_cmtpath=/storage/epp2/t2k/software/ND280/v9r7p9
ecalRecon_project=ND280
ecalRecon_project_release=v9r7p9
ecalRecon_cppflags= -DECALRECON_USED 
ecalRecon_linkopts= -L$(ECALRECONROOT)/$(ecalRecon_tag) -lecalRecon -lTreePlayer -lMLP -lTMVA
ecalRecon_stamps= $(ECALRECONROOT)/$(ecalRecon_tag)/ecalRecon.stamp
p0dRecon_tag=$(tag)
P0DRECONROOT=/storage/epp2/t2k/software/ND280/v9r7p9/p0dRecon/v7r3p9
p0dRecon_root=/storage/epp2/t2k/software/ND280/v9r7p9/p0dRecon/v7r3p9
P0DRECONVERSION=v7r3p9
p0dRecon_cmtpath=/storage/epp2/t2k/software/ND280/v9r7p9
p0dRecon_project=ND280
p0dRecon_project_release=v9r7p9
p0dRecon_cppflags= -DP0DRECON_USED 
p0dRecon_linkopts= -L$(P0DRECONROOT)/$(p0dRecon_tag) -lp0dRecon -lSpectrum -lSpectrumPainter
p0dRecon_stamps= $(P0DRECONROOT)/$(p0dRecon_tag)/p0dRecon.stamp
p0decalRecon_tag=$(tag)
P0DECALRECONROOT=/storage/epp2/t2k/software/ND280/v9r7p9/p0decalRecon/v0r19
p0decalRecon_root=/storage/epp2/t2k/software/ND280/v9r7p9/p0decalRecon/v0r19
P0DECALRECONVERSION=v0r19
p0decalRecon_cmtpath=/storage/epp2/t2k/software/ND280/v9r7p9
p0decalRecon_project=ND280
p0decalRecon_project_release=v9r7p9
p0decalRecon_cppflags= -DP0DECALRECON_USED 
p0decalRecon_linkopts= -L$(P0DECALRECONROOT)/$(p0decalRecon_tag) -lp0decalRecon -lTreePlayer -lMLP -lTMVA
p0decalRecon_stamps= $(P0DECALRECONROOT)/$(p0decalRecon_tag)/p0decalRecon.stamp
smrdRecon_tag=$(tag)
SMRDRECONROOT=/storage/epp2/t2k/software/ND280/v9r7p9/smrdRecon/v3r3p3
smrdRecon_root=/storage/epp2/t2k/software/ND280/v9r7p9/smrdRecon/v3r3p3
SMRDRECONVERSION=v3r3p3
smrdRecon_cmtpath=/storage/epp2/t2k/software/ND280/v9r7p9
smrdRecon_project=ND280
smrdRecon_project_release=v9r7p9
smrdCalib_tag=$(tag)
SMRDCALIBROOT=/storage/epp2/t2k/software/ND280/v9r7p9/smrdCalib/v1r13
smrdCalib_root=/storage/epp2/t2k/software/ND280/v9r7p9/smrdCalib/v1r13
SMRDCALIBVERSION=v1r13
smrdCalib_cmtpath=/storage/epp2/t2k/software/ND280/v9r7p9
smrdCalib_project=ND280
smrdCalib_project_release=v9r7p9
smrdCalib_cppflags= -DSMRDCALIB_USED 
smrdCalib_linkopts= -L$(SMRDCALIBROOT)/$(smrdCalib_tag) -lsmrdCalib 
smrdCalib_stamps= $(SMRDCALIBROOT)/$(smrdCalib_tag)/smrdCalib.stamp
smrdRecon_cppflags= -DSMRDRECON_USED
smrdRecon_linkopts= -L$(SMRDRECONROOT)/$(smrdRecon_tag) -lsmrdRecon 
smrdRecon_stamps= $(SMRDRECONROOT)/$(smrdRecon_tag)/smrdRecon.stamp
oaRecon_cppflags= -DOARECON_USED 
oaRecon_linkopts= -L$(OARECONROOT)/$(oaRecon_tag) -loaRecon 
oaRecon_stamps= $(OARECONROOT)/$(oaRecon_tag)/oaRecon.stamp
oaAnalysis_dependencies= warnCALIBRECON
oaAnalysis_cppflags= -DOAANALYSIS_USED 
oaAnalysis_linkopts= -L$(OAANALYSISROOT)/$(oaAnalysis_tag) -loaAnalysis 
oaAnalysis_stamps= $(OAANALYSISROOT)/$(oaAnalysis_tag)/oaAnalysis.stamp
tag=amd64_linux26
package=myND280
version=v0r0
PACKAGE_ROOT=$(MYND280ROOT)
srcdir=../src
bin=../$(myND280_tag)/
BIN=/home/physics/phuidv/Documents/t2kstuff/recon/myND280/v0r0/$(myND280_tag)/
javabin=../classes/
mgrdir=cmt
cmt_installarea_paths= $(cmt_installarea_prefix)/$(CMTCONFIG)/bin
use_linkopts= $(cmt_installarea_linkopts)   $(myND280_linkopts)  $(oaAnalysis_linkopts)  $(oaRecon_linkopts)  $(trackerRecon_linkopts)  $(fgdRecon_linkopts)  $(smrdRecon_linkopts)  $(tpcRecon_linkopts)  $(p0decalRecon_linkopts)  $(ecalRecon_linkopts)  $(oaRecPack_linkopts)  $(oaCalib_linkopts)  $(oaApplyAlign_linkopts)  $(sbcat_linkopts)  $(p0dRecon_linkopts)  $(smrdCalib_linkopts)  $(oaGeomInfo_linkopts)  $(oaUtility_linkopts)  $(magnetCalib_linkopts)  $(fgdRawData_linkopts)  $(tfbApplyCalib_linkopts)  $(oaSlowControlDatabase_linkopts)  $(oaBeamData_linkopts)  $(oaUnpack_linkopts)  $(oaRawEvent_linkopts)  $(oaRuntimeParameters_linkopts)  $(oaChanInfo_linkopts)  $(oaOfflineDatabase_linkopts)  $(MinosDBI_linkopts)  $(oaEvent_linkopts)  $(testBase_linkopts)  $(RECPACK_linkopts)  $(oaDataQuality_linkopts)  $(nd280Policy_linkopts)  $(ROOT_linkopts)  $(MYSQL_linkopts)  $(CLHEP_linkopts)  $(EXTERN_linkopts) 
ND280_installarea_prefix=$(cmt_installarea_prefix)
ND280_installarea_prefix_remove=$(ND280_installarea_prefix)
use_requirements=requirements $(CMTROOT)/mgr/requirements $(OAANALYSISROOT)/cmt/requirements $(OARECONROOT)/cmt/requirements $(TRACKERRECONROOT)/cmt/requirements $(FGDRECONROOT)/cmt/requirements $(SMRDRECONROOT)/cmt/requirements $(TPCRECONROOT)/cmt/requirements $(P0DECALRECONROOT)/cmt/requirements $(ECALRECONROOT)/cmt/requirements $(OARECPACKROOT)/cmt/requirements $(OACALIBROOT)/cmt/requirements $(OAAPPLYALIGNROOT)/cmt/requirements $(SBCATROOT)/cmt/requirements $(P0DRECONROOT)/cmt/requirements $(SMRDCALIBROOT)/cmt/requirements $(OAGEOMINFOROOT)/cmt/requirements $(OAUTILITYROOT)/cmt/requirements $(MAGNETCALIBROOT)/cmt/requirements $(FGDRAWDATAROOT)/cmt/requirements $(TFBAPPLYCALIBROOT)/cmt/requirements $(OASLOWCONTROLDATABASEROOT)/cmt/requirements $(OABEAMDATAROOT)/cmt/requirements $(OAUNPACKROOT)/cmt/requirements $(OARAWEVENTROOT)/cmt/requirements $(OARUNTIMEPARAMETERSROOT)/cmt/requirements $(OACHANINFOROOT)/cmt/requirements $(OAOFFLINEDATABASEROOT)/cmt/requirements $(MINOSDBIROOT)/cmt/requirements $(OAEVENTROOT)/cmt/requirements $(TESTBASEROOT)/cmt/requirements $(RECPACKROOT)/cmt/requirements $(OADATAQUALITYROOT)/cmt/requirements $(ND280POLICYROOT)/cmt/requirements $(ROOTROOT)/cmt/requirements $(MYSQLROOT)/cmt/requirements $(CLHEPROOT)/cmt/requirements $(EXTERNROOT)/cmt/requirements 
use_includes= $(ppcmd)"$(oaAnalysis_root)/src" $(ppcmd)"$(oaRecon_root)/src" $(ppcmd)"$(trackerRecon_root)/src" $(ppcmd)"$(fgdRecon_root)/src" $(ppcmd)"$(smrdRecon_root)/src" $(ppcmd)"$(tpcRecon_root)/src" $(ppcmd)"$(p0decalRecon_root)/src" $(ppcmd)"$(ecalRecon_root)/src" $(ppcmd)"$(oaRecPack_root)/src" $(ppcmd)"$(oaCalib_root)/src" $(ppcmd)"$(oaApplyAlign_root)/src" $(ppcmd)"$(sbcat_root)/src" $(ppcmd)"$(p0dRecon_root)/src" $(ppcmd)"$(smrdCalib_root)/src" $(ppcmd)"$(oaGeomInfo_root)/src" $(ppcmd)"$(oaUtility_root)/src" $(ppcmd)"$(magnetCalib_root)/src" $(ppcmd)"$(fgdRawData_root)/src" $(ppcmd)"$(tfbApplyCalib_root)/src" $(ppcmd)"$(oaSlowControlDatabase_root)/src" $(ppcmd)"$(oaBeamData_root)/src" $(ppcmd)"$(oaUnpack_root)/src" $(ppcmd)"$(oaRawEvent_root)/src" $(ppcmd)"$(oaRuntimeParameters_root)/src" $(ppcmd)"$(oaChanInfo_root)/src" $(ppcmd)"$(oaOfflineDatabase_root)/src" $(ppcmd)"$(MinosDBI_root)/src" $(ppcmd)"$(oaEvent_root)/src" $(ppcmd)"$(testBase_root)/src" $(ppcmd)"/storage/epp2/t2k/software/ND280/v9r7p9/RECPACK/v1r17p1/amd64_linux26" $(ppcmd)"$(oaDataQuality_root)/src" $(ppcmd)"$(nd280Policy_root)/src" $(ppcmd)"/storage/epp2/t2k/software/ND280/v9r7p9/ROOT/v5r28p00n01/amd64_linux26/include/root" $(ppcmd)"none" $(ppcmd)"/storage/epp2/t2k/software/ND280/v9r7p9/MYSQL/v5r051an01/amd64_linux26/include/mysql" $(ppcmd)"none" $(ppcmd)"/storage/epp2/t2k/software/ND280/v9r7p9/CLHEP/v2r0p4n05/amd64_linux26/include" $(ppcmd)"$(EXTERN_root)/src" 
use_fincludes= $(use_includes)
use_stamps= $(myND280_stamps)  $(oaAnalysis_stamps)  $(oaRecon_stamps)  $(trackerRecon_stamps)  $(fgdRecon_stamps)  $(smrdRecon_stamps)  $(tpcRecon_stamps)  $(p0decalRecon_stamps)  $(ecalRecon_stamps)  $(oaRecPack_stamps)  $(oaCalib_stamps)  $(oaApplyAlign_stamps)  $(sbcat_stamps)  $(p0dRecon_stamps)  $(smrdCalib_stamps)  $(oaGeomInfo_stamps)  $(oaUtility_stamps)  $(magnetCalib_stamps)  $(fgdRawData_stamps)  $(tfbApplyCalib_stamps)  $(oaSlowControlDatabase_stamps)  $(oaBeamData_stamps)  $(oaUnpack_stamps)  $(oaRawEvent_stamps)  $(oaRuntimeParameters_stamps)  $(oaChanInfo_stamps)  $(oaOfflineDatabase_stamps)  $(MinosDBI_stamps)  $(oaEvent_stamps)  $(testBase_stamps)  $(RECPACK_stamps)  $(oaDataQuality_stamps)  $(nd280Policy_stamps)  $(ROOT_stamps)  $(MYSQL_stamps)  $(CLHEP_stamps)  $(EXTERN_stamps) 
use_cflags=  $(myND280_cflags)  $(oaAnalysis_cflags)  $(oaRecon_cflags)  $(trackerRecon_cflags)  $(fgdRecon_cflags)  $(smrdRecon_cflags)  $(tpcRecon_cflags)  $(p0decalRecon_cflags)  $(ecalRecon_cflags)  $(oaRecPack_cflags)  $(oaCalib_cflags)  $(oaApplyAlign_cflags)  $(sbcat_cflags)  $(p0dRecon_cflags)  $(smrdCalib_cflags)  $(oaGeomInfo_cflags)  $(oaUtility_cflags)  $(magnetCalib_cflags)  $(fgdRawData_cflags)  $(tfbApplyCalib_cflags)  $(oaSlowControlDatabase_cflags)  $(oaBeamData_cflags)  $(oaUnpack_cflags)  $(oaRawEvent_cflags)  $(oaRuntimeParameters_cflags)  $(oaChanInfo_cflags)  $(oaOfflineDatabase_cflags)  $(MinosDBI_cflags)  $(oaEvent_cflags)  $(testBase_cflags)  $(RECPACK_cflags)  $(oaDataQuality_cflags)  $(nd280Policy_cflags)  $(ROOT_cflags)  $(MYSQL_cflags)  $(CLHEP_cflags)  $(EXTERN_cflags) 
use_pp_cflags=  $(myND280_pp_cflags)  $(oaAnalysis_pp_cflags)  $(oaRecon_pp_cflags)  $(trackerRecon_pp_cflags)  $(fgdRecon_pp_cflags)  $(smrdRecon_pp_cflags)  $(tpcRecon_pp_cflags)  $(p0decalRecon_pp_cflags)  $(ecalRecon_pp_cflags)  $(oaRecPack_pp_cflags)  $(oaCalib_pp_cflags)  $(oaApplyAlign_pp_cflags)  $(sbcat_pp_cflags)  $(p0dRecon_pp_cflags)  $(smrdCalib_pp_cflags)  $(oaGeomInfo_pp_cflags)  $(oaUtility_pp_cflags)  $(magnetCalib_pp_cflags)  $(fgdRawData_pp_cflags)  $(tfbApplyCalib_pp_cflags)  $(oaSlowControlDatabase_pp_cflags)  $(oaBeamData_pp_cflags)  $(oaUnpack_pp_cflags)  $(oaRawEvent_pp_cflags)  $(oaRuntimeParameters_pp_cflags)  $(oaChanInfo_pp_cflags)  $(oaOfflineDatabase_pp_cflags)  $(MinosDBI_pp_cflags)  $(oaEvent_pp_cflags)  $(testBase_pp_cflags)  $(RECPACK_pp_cflags)  $(oaDataQuality_pp_cflags)  $(nd280Policy_pp_cflags)  $(ROOT_pp_cflags)  $(MYSQL_pp_cflags)  $(CLHEP_pp_cflags)  $(EXTERN_pp_cflags) 
use_cppflags=  $(myND280_cppflags)  $(oaAnalysis_cppflags)  $(oaRecon_cppflags)  $(trackerRecon_cppflags)  $(fgdRecon_cppflags)  $(smrdRecon_cppflags)  $(tpcRecon_cppflags)  $(p0decalRecon_cppflags)  $(ecalRecon_cppflags)  $(oaRecPack_cppflags)  $(oaCalib_cppflags)  $(oaApplyAlign_cppflags)  $(sbcat_cppflags)  $(p0dRecon_cppflags)  $(smrdCalib_cppflags)  $(oaGeomInfo_cppflags)  $(oaUtility_cppflags)  $(magnetCalib_cppflags)  $(fgdRawData_cppflags)  $(tfbApplyCalib_cppflags)  $(oaSlowControlDatabase_cppflags)  $(oaBeamData_cppflags)  $(oaUnpack_cppflags)  $(oaRawEvent_cppflags)  $(oaRuntimeParameters_cppflags)  $(oaChanInfo_cppflags)  $(oaOfflineDatabase_cppflags)  $(MinosDBI_cppflags)  $(oaEvent_cppflags)  $(testBase_cppflags)  $(RECPACK_cppflags)  $(oaDataQuality_cppflags)  $(nd280Policy_cppflags)  $(ROOT_cppflags)  $(MYSQL_cppflags)  $(CLHEP_cppflags)  $(EXTERN_cppflags) 
use_pp_cppflags=  $(myND280_pp_cppflags)  $(oaAnalysis_pp_cppflags)  $(oaRecon_pp_cppflags)  $(trackerRecon_pp_cppflags)  $(fgdRecon_pp_cppflags)  $(smrdRecon_pp_cppflags)  $(tpcRecon_pp_cppflags)  $(p0decalRecon_pp_cppflags)  $(ecalRecon_pp_cppflags)  $(oaRecPack_pp_cppflags)  $(oaCalib_pp_cppflags)  $(oaApplyAlign_pp_cppflags)  $(sbcat_pp_cppflags)  $(p0dRecon_pp_cppflags)  $(smrdCalib_pp_cppflags)  $(oaGeomInfo_pp_cppflags)  $(oaUtility_pp_cppflags)  $(magnetCalib_pp_cppflags)  $(fgdRawData_pp_cppflags)  $(tfbApplyCalib_pp_cppflags)  $(oaSlowControlDatabase_pp_cppflags)  $(oaBeamData_pp_cppflags)  $(oaUnpack_pp_cppflags)  $(oaRawEvent_pp_cppflags)  $(oaRuntimeParameters_pp_cppflags)  $(oaChanInfo_pp_cppflags)  $(oaOfflineDatabase_pp_cppflags)  $(MinosDBI_pp_cppflags)  $(oaEvent_pp_cppflags)  $(testBase_pp_cppflags)  $(RECPACK_pp_cppflags)  $(oaDataQuality_pp_cppflags)  $(nd280Policy_pp_cppflags)  $(ROOT_pp_cppflags)  $(MYSQL_pp_cppflags)  $(CLHEP_pp_cppflags)  $(EXTERN_pp_cppflags) 
use_fflags=  $(myND280_fflags)  $(oaAnalysis_fflags)  $(oaRecon_fflags)  $(trackerRecon_fflags)  $(fgdRecon_fflags)  $(smrdRecon_fflags)  $(tpcRecon_fflags)  $(p0decalRecon_fflags)  $(ecalRecon_fflags)  $(oaRecPack_fflags)  $(oaCalib_fflags)  $(oaApplyAlign_fflags)  $(sbcat_fflags)  $(p0dRecon_fflags)  $(smrdCalib_fflags)  $(oaGeomInfo_fflags)  $(oaUtility_fflags)  $(magnetCalib_fflags)  $(fgdRawData_fflags)  $(tfbApplyCalib_fflags)  $(oaSlowControlDatabase_fflags)  $(oaBeamData_fflags)  $(oaUnpack_fflags)  $(oaRawEvent_fflags)  $(oaRuntimeParameters_fflags)  $(oaChanInfo_fflags)  $(oaOfflineDatabase_fflags)  $(MinosDBI_fflags)  $(oaEvent_fflags)  $(testBase_fflags)  $(RECPACK_fflags)  $(oaDataQuality_fflags)  $(nd280Policy_fflags)  $(ROOT_fflags)  $(MYSQL_fflags)  $(CLHEP_fflags)  $(EXTERN_fflags) 
use_pp_fflags=  $(myND280_pp_fflags)  $(oaAnalysis_pp_fflags)  $(oaRecon_pp_fflags)  $(trackerRecon_pp_fflags)  $(fgdRecon_pp_fflags)  $(smrdRecon_pp_fflags)  $(tpcRecon_pp_fflags)  $(p0decalRecon_pp_fflags)  $(ecalRecon_pp_fflags)  $(oaRecPack_pp_fflags)  $(oaCalib_pp_fflags)  $(oaApplyAlign_pp_fflags)  $(sbcat_pp_fflags)  $(p0dRecon_pp_fflags)  $(smrdCalib_pp_fflags)  $(oaGeomInfo_pp_fflags)  $(oaUtility_pp_fflags)  $(magnetCalib_pp_fflags)  $(fgdRawData_pp_fflags)  $(tfbApplyCalib_pp_fflags)  $(oaSlowControlDatabase_pp_fflags)  $(oaBeamData_pp_fflags)  $(oaUnpack_pp_fflags)  $(oaRawEvent_pp_fflags)  $(oaRuntimeParameters_pp_fflags)  $(oaChanInfo_pp_fflags)  $(oaOfflineDatabase_pp_fflags)  $(MinosDBI_pp_fflags)  $(oaEvent_pp_fflags)  $(testBase_pp_fflags)  $(RECPACK_pp_fflags)  $(oaDataQuality_pp_fflags)  $(nd280Policy_pp_fflags)  $(ROOT_pp_fflags)  $(MYSQL_pp_fflags)  $(CLHEP_pp_fflags)  $(EXTERN_pp_fflags) 
use_libraries= $(oaAnalysis_libraries)  $(oaRecon_libraries)  $(trackerRecon_libraries)  $(fgdRecon_libraries)  $(smrdRecon_libraries)  $(tpcRecon_libraries)  $(p0decalRecon_libraries)  $(ecalRecon_libraries)  $(oaRecPack_libraries)  $(oaCalib_libraries)  $(oaApplyAlign_libraries)  $(sbcat_libraries)  $(p0dRecon_libraries)  $(smrdCalib_libraries)  $(oaGeomInfo_libraries)  $(oaUtility_libraries)  $(magnetCalib_libraries)  $(fgdRawData_libraries)  $(tfbApplyCalib_libraries)  $(oaSlowControlDatabase_libraries)  $(oaBeamData_libraries)  $(oaUnpack_libraries)  $(oaRawEvent_libraries)  $(oaRuntimeParameters_libraries)  $(oaChanInfo_libraries)  $(oaOfflineDatabase_libraries)  $(MinosDBI_libraries)  $(oaEvent_libraries)  $(testBase_libraries)  $(RECPACK_libraries)  $(oaDataQuality_libraries)  $(nd280Policy_libraries)  $(ROOT_libraries)  $(MYSQL_libraries)  $(CLHEP_libraries)  $(EXTERN_libraries) 
includes= $(ppcmd)"$(srcdir)" $(use_includes)
fincludes= $(includes)
analysis_use_linkopts=  $(myND280_linkopts)  $(oaAnalysis_linkopts)  $(oaRecon_linkopts)  $(trackerRecon_linkopts)  $(fgdRecon_linkopts)  $(smrdRecon_linkopts)  $(tpcRecon_linkopts)  $(p0decalRecon_linkopts)  $(ecalRecon_linkopts)  $(oaRecPack_linkopts)  $(oaCalib_linkopts)  $(oaApplyAlign_linkopts)  $(sbcat_linkopts)  $(p0dRecon_linkopts)  $(smrdCalib_linkopts)  $(oaGeomInfo_linkopts)  $(oaUtility_linkopts)  $(magnetCalib_linkopts)  $(fgdRawData_linkopts)  $(tfbApplyCalib_linkopts)  $(oaSlowControlDatabase_linkopts)  $(oaBeamData_linkopts)  $(oaUnpack_linkopts)  $(oaRawEvent_linkopts)  $(oaRuntimeParameters_linkopts)  $(oaChanInfo_linkopts)  $(oaOfflineDatabase_linkopts)  $(MinosDBI_linkopts)  $(oaEvent_linkopts)  $(testBase_linkopts)  $(RECPACK_linkopts)  $(oaDataQuality_linkopts)  $(nd280Policy_linkopts)  $(ROOT_linkopts)  $(MYSQL_linkopts)  $(CLHEP_linkopts)  $(EXTERN_linkopts) 
constituents= analysis 
all_constituents= $(constituents)
constituentsclean= analysisclean 
all_constituentsclean= $(constituentsclean)
cmt_actions_constituents= make warnCALIBRECON 
cmt_actions_constituentsclean= warnCALIBRECONclean makeclean 
